import Link from "next/link";
import type { Metadata } from "next";
export const metadata: Metadata = { title: "AI receptionists for contractors", description: "Explore an AI receptionist pilot for missed calls, after-hours inquiries, and lead capture. Start with a free call-flow review." };
export default function VoicePage() {
 return <>
 <section className="studio-wrap studio-section"><p className="eyebrow">AI receptionist / Pilot program</p><div className="section-heading"><h1 className="display text-5xl leading-tight sm:text-7xl">You’re on the job.<br/><em>The phone still rings.</em></h1><p>Let’s design a better way to handle missed calls. An AI receptionist pilot for contractors and home service businesses, built around your hours, services, and handoff rules.</p></div><Link className="btn btn-fill" href="/contact?service=ai-receptionist">Request a free call-flow review ↗</Link><p className="mt-5 text-sm text-[var(--color-ink-soft)]">Consultation first. Scope, costs, and launch criteria agreed before setup.</p></section>
 <section className="work-section"><div className="studio-wrap studio-section"><p className="eyebrow">Start with one useful job</p><h2 className="display mt-5 text-4xl sm:text-5xl">Catch the inquiry.<br/>Keep a person in the loop.</h2><div className="offer-grid mt-10">{[["01","After-hours intake","Collect the caller’s name, callback number, service needed, and job location using a business-approved script."],["02","Clear next steps","Answer approved common questions and capture appointment requests. Confirm bookings only when a calendar integration is tested and included."],["03","A human handoff","Route agreed situations to your team. If nobody answers, collect a callback request without promising an immediate response."]].map(([n,t,d])=><article className="offer-card" key={n}><p className="eyebrow">{n}</p><h3 className="display">{t}</h3><p>{d}</p></article>)}</div></div></section>
 <section className="studio-wrap studio-section"><div className="section-heading"><p className="eyebrow">A managed service</p><h2 className="display">Set it up properly.<br/>Improve it every month.</h2><p>A one-time setup fee covers the agreed call flow and testing. Monthly management covers monitoring, approved updates, and support. Calling costs and any usage allowance are stated separately in your proposal.</p></div><div className="process-list">{[["01","Review your calls","Discuss missed calls, call volume, business hours, and how your team follows up. No call recordings are required for the initial review."],["02","Define and test a pilot","Choose one number or after-hours flow. Agree on the script, human transfer, failure handling, usage cap, and acceptance checks."],["03","Launch with oversight","Review call outcomes, failed handoffs, and lead quality. Expand only after the pilot meets the agreed standards."]].map(([n,t,d])=><div key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></section>
 <section className="studio-wrap faq-section"><div><p className="eyebrow">Straight answers</p><h2 className="display">Useful automation.<br/>Clear boundaries.</h2></div><div>{[["Is this available to try right now?","We are taking inquiries for scoped pilots. This page is not a live voice demo; the assistant and phone integration are configured and tested for each business before launch."],["Will callers know it is AI?","The planned greeting identifies the assistant as automated. Recording and transcript settings are agreed before launch, alongside any required notices."],["Can it quote a job or handle an emergency?","It should not invent prices, promise availability, or provide emergency advice. We define approved answers, escalation instructions, and limits with your team."],["Can I keep my existing number?","We review your phone provider and forwarding options first. Compatibility and any changes are confirmed in the proposal."],["How much does it cost?","You receive a setup price, monthly management fee, and clear calling usage terms after the review. No unlimited calling or guaranteed revenue is promised."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 <section className="closing-cta"><div className="studio-wrap"><p className="eyebrow">Start with your missed calls</p><h2 className="display">Find the gap.<br/><em>Then build the right fix.</em></h2><Link className="btn btn-fill" href="/contact?service=ai-receptionist">Request a free call-flow review ↗</Link></div></section>
 </>;
}
