import Link from "next/link";
import { site } from "@/lib/site";
import { services } from "@/lib/services";

export default function HomePage() {
  return <div>
    <section className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-16 lg:grid-cols-[1.4fr_1fr] lg:py-24">
      <div><p className="stamp">Maurice Garcia · Independent web developer</p>
        <h1 className="display mt-6 text-5xl leading-[1.02] sm:text-7xl">Your next chapter<br/><span className="text-[var(--color-rust)]">starts with a website.</span></h1>
        <p className="mt-6 max-w-xl text-lg leading-relaxed text-[var(--color-ink-soft)]">I build websites and custom tools for people growing a business. From your first page to a better way to take bookings, sell products, or manage work.</p>
        <div className="mt-8 flex flex-wrap gap-3"><Link href="/contact" className="btn btn-fill">Plan my website →</Link><Link href="/work" className="btn btn-ghost">See my work</Link></div>
        <p className="mt-4 text-sm text-[var(--color-ink-soft)]">Start with an idea. Get a clear scope before you commit.</p>
      </div>
      <div className="relative border border-[var(--color-rule)] p-3"><img src={site.photo} alt="Maurice Garcia" className="aspect-[4/5] w-full object-cover object-[center_20%]"/><div className="border-t border-[var(--color-rule)] px-3 py-5"><p className="stamp">A direct working relationship</p><p className="display mt-2 text-2xl">Your idea. My hands on the build.</p></div></div>
    </section>
    <section className="border-y border-[var(--color-rule)]"><div className="mx-auto max-w-6xl px-5 py-16"><p className="stamp">Ways we can work together</p><h2 className="display mt-4 text-4xl">Build it. Improve it. Keep it useful.</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{services.slice(0,3).map((s,i) => <article key={s.slug} className="flex flex-col border border-[var(--color-rule)] p-6"><p className="stamp">0{i+1} · {s.price}</p><h3 className="display mt-5 text-3xl">{s.name}</h3><p className="mt-4 flex-1 leading-relaxed text-[var(--color-ink-soft)]">{s.summary}</p><Link href={`/contact?service=${s.slug}`} className="mt-8 underline underline-offset-4">Talk about this →</Link></article>)}</div><p className="mt-6 text-[var(--color-ink-soft)]">Need something more involved? <Link href="/services" className="underline">Explore custom software and other services.</Link></p></div></section>
    <section className="mx-auto grid max-w-6xl gap-12 px-5 py-20 md:grid-cols-2"><div><p className="stamp">Selected work · Custom software</p><h2 className="display mt-4 text-4xl">More than a good-looking page.</h2><p className="mt-5 text-lg leading-relaxed text-[var(--color-ink-soft)]">Pipeline CRM was built for Don Howard Construction / Painting to handle leads, estimates, invoices, deposits, and jobs. Bring me the way your business works, and we can plan the right tools around it.</p><Link href="/work" className="btn btn-ghost mt-6">Explore the project</Link></div><div className="border-l-2 border-[var(--color-rust)] pl-8"><p className="stamp">From idea to launch</p><ol className="mt-6 space-y-7">{[["01 / Tell me what you need","A short project brief starts the conversation. You do not need a technical specification."],["02 / Agree on a plan","We define the pages, features, price, and timeline before the build."],["03 / Build, review, and launch","Review the work together, then launch with a handoff and an optional care plan."]].map(([title,body]) => <li key={title}><h3 className="display text-2xl">{title}</h3><p className="mt-2 text-[var(--color-ink-soft)]">{body}</p></li>)}</ol></div></section>
    <section className="border-t border-[var(--color-rule)]"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-8 px-5 py-16"><div><p className="stamp">Have something in mind?</p><h2 className="display mt-4 text-4xl">You do not need it all figured out.</h2><p className="mt-4 text-[var(--color-ink-soft)]">Tell me what you want your business to do next.</p></div><Link href="/contact" className="btn btn-fill">Plan my website →</Link></div></section>
  </div>;
}
